### ISSUE TITLE
Upgrade Project to Spring Boot 3

### ISSUE THREAD

**Issue by sami-eljabali** [seljabali/todo-list-spring-boot-webflux-kotlin#2]
Feel free to create a new project from [https://start.spring.io](https://start.spring.io) to replace this one.

**Comment by hantsy** [comment]
Currently Spring Boot 3 just started its first milestone, I think at the end of this year, maybe it will release a stable version(new native build, new Spring observablity module).

I have created a branch and PR for it, the current codes is working well with Spring Boot 3.0.0-M1, I only changed the version and add Maven URL for deps and Gradle plugins.

**Comment by hantsy** [comment]
see: https://github.com/seljabali/todo-list-spring-boot-webflux-kotlin/pull/14
