### ISSUE TITLE
Refactor project to use modules

### ISSUE THREAD

**Issue by sami-eljabali** [seljabali/todo-list-spring-boot-webflux-kotlin#4]
- Database 
	- Database models
	- Database Repositories

- Network (networking models)
	- Network models
	- Network Repositories

- App (controllers)
	- Depends on Database & Network

**Comment by hantsy** [comment]
The project structure you show me in last meeting is ok for most applications, esp the traditional Java web application built with Spring(none Spring Boot) or Java EE.

But for the latest Spring Boot, Micronaut, Quarkus, it follows another principle of 12 factor app, [Convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration), it will simplify a lot of hard work for configurations, numerous configs are hidden and auto configured by Spring Boot when scanning the project classpaths. 

I have used multi-modules in the past years, the completest project includes over 50 maven modules. But after migrated to Spring Boot, I gave up the split-by-layers/components strategy, but use the split-by-features(when the application is increasingly complex) which follows the popular Microservice pattern, move some standalone features(a domain related, such as payment, email, notification) to standalone projects, used a `Gateway` at the front to serve client apps, AWS Gateway/Spring Cloud Gateway is a good case for this purpose.
