### ISSUE TITLE
CRUD of Todos

### ISSUE THREAD

**Issue by sami-eljabali** [seljabali/todo-list-spring-boot-webflux-kotlin#9]
`Todo` Model:
- UUID
- Title (String)
- Content (String)
- Create Date (ISO date time format)(UTC) (String)

Create endpoints to do Create, Read, Update, & Delete.

**Comment by sami-eljabali** [comment]
For date time parsing please use [Kotlin.Time](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/) or [Java.Time](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html)

**Comment by sami-eljabali** [comment]
This [project](https://github.com/seljabali/java-time-fun) I wrote may help with parsing in Kotlin using Java Time.

**Comment by hantsy** [comment]
Done, but this time, I used Long as id type.

**Comment by hantsy** [comment]
Included an external completed field to mark it as completed, also enabled Spring Data R2dbc auditing to fill the createdBy automaticially.
